"""Standalone Bazzite UI mockup. No GPIO, USB or firmware changes."""
from pathlib import Path
import base64,json
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parent.parent
OUT=ROOT/'outputs/Resource-Panel/simulations/bazzite'
font=base64.b64encode((OUT/'fonts/DroidSansMNerdFontMono-Regular.otf').read_bytes()).decode()
photo=base64.b64encode((OUT.parent/'day-frame-2s.jpg').read_bytes()).decode()
css=f'''@font-face{{font-family:Droid;src:url(data:font/otf;base64,{font}) format("opentype");font-weight:400}}'''+'''
*{box-sizing:border-box}body{margin:0;background:#ecebe5;color:#243d35;font:14px Droid,monospace}button,input,select{font:inherit}button{cursor:pointer;border:0;color:#fff8e8;background:#374943cc;border-radius:8px;height:34px}button:focus-visible{outline:2px solid #ffc7d5}h1{font-size:22px;font-weight:400}.notes{max-width:820px;padding:20px;line-height:1.6}.notes p{margin:6px 0}#device{position:relative;width:894px;height:565px;background:#090909}#screen{transform:scaleY(1.0077160494);transform-origin:top left;position:absolute;left:47px;top:26px;width:800px;height:480px;overflow:hidden;background:#10201d;color:#fff3da}#scene{position:absolute;inset:0;width:800px;height:480px}.settings{position:absolute;left:16px;top:16px;width:125px;height:38px}#card{position:absolute;left:476px;top:16px;width:308px;height:448px;border:1px solid #afa88d5a;border-radius:16px;background:#3a5048eb;padding:14px}#card div,#card button{position:absolute}.title{left:14px;top:12px;font-size:24px;color:#ffc7d5}.host{left:14px;top:46px;font-size:14px}.metric{font-size:24px;line-height:27px;white-space:pre}.metric-value{color:#ffc477}.cpu{left:14px;top:78px}.temp{left:159px;top:78px}.ram{left:14px;top:162px}.disk{left:14px;top:259px}.link{left:14px;top:327px;font-size:12px}.sleep{left:14px;top:360px;width:133px}.sound{left:157px;top:360px;width:135px}.led{left:14px;top:401px;width:278px;background:#654e60e0;color:#ffdae5}.overlay{position:absolute;left:190px;top:45px;width:420px;height:390px;padding:24px;background:#243d35fa;border:1px solid #afa88d;border-radius:16px;box-shadow:0 5px 25px #0007}.overlay[hidden]{display:none}.overlay h2{font-size:24px;color:#ffc7d5;font-weight:400;margin:0 0 10px}.overlay p{font-size:13px;line-height:1.5}.row{display:flex;gap:10px;margin:18px 0;align-items:center}.swatch{width:40px;height:40px;border:2px solid #fff4}.overlay label{display:block;margin-top:14px}.overlay input[type=range]{width:100%;accent-color:#ffc7d5}.overlay select{background:#374943;color:#fff3da;border:1px solid #afa88d;padding:6px;width:100%}.close{position:absolute;right:16px;top:16px;width:32px}.indicator{width:20px;height:20px;border-radius:50%;background:#ffc7d5;box-shadow:0 0 16px #ffc7d5}#preview-state{font-size:12px;color:#dbc9b8}.ruler{width:50mm;border-top:1px solid #243d35;text-align:center;margin-top:8mm;padding-top:3mm}@media print{@page{size:A4;margin:15mm}.notes,.ruler{display:none}body{background:white}#device{width:120.7mm;height:76.3mm}#screen{left:6.35mm;top:3.5mm;transform:scale(.5102362205,.5141732283);transform-origin:top left}}
'''
body=f'''<div id="device"><div id="screen"><img id="scene" alt="Daytime ronin at the onsen" src="data:image/jpeg;base64,{photo}"><button class="settings" id="settings">&#xf013; SETTINGS</button><div id="card"><div class="title">MOUNTAIN REFUGE</div><div class="host">bc250-bazzite | Linux</div><div class="metric cpu">CPU LOAD\n<span class="metric-value">8.6 %</span></div><div class="metric temp">CPU TEMP\n<span class="metric-value">47.0 C</span></div><div class="metric ram">RAM\n<span class="metric-value">41.6 %\n3.2 / 7.7 GiB</span></div><div class="metric disk">SYSTEM DISK\n<span class="metric-value">6.8 % used</span></div><div class="link">USB connected - live readings</div><button class="sleep">SLEEP DISPLAY</button><button class="sound" id="sound">MUTE / SOUND</button><button class="led" id="led">&#xf0eb; LED CONTROLLER · 48</button></div><section class="overlay" id="led-panel" hidden><button class="close" id="close" aria-label="Close LED controls">×</button><h2>&#xf0eb; NEOPIXEL</h2><p>2 &times; 24 RGB pixels &bull; wiring pending</p><div class="row"><span class="indicator" id="indicator"></span><button id="power" style="width:110px">LIGHTS ON</button><span id="preview-state">Sakura / 30%</span></div><div class="row"><button class="swatch" data-name="Sakura" data-color="#ffc7d5" style="background:#ffc7d5" aria-label="Sakura pink"></button><button class="swatch" data-name="Lantern" data-color="#ffc477" style="background:#ffc477" aria-label="Lantern amber"></button><button class="swatch" data-name="Onsen" data-color="#88b7ad" style="background:#88b7ad" aria-label="Onsen teal"></button><button class="swatch" data-name="Moonlight" data-color="#96a9e1" style="background:#96a9e1" aria-label="Moonlight blue"></button></div><label for="brightness">Brightness <span id="percent">30%</span></label><input id="brightness" type="range" min="0" max="100" value="30"><label for="effect">Effect</label><select id="effect"><option>Steady</option><option>Gentle breathing</option><option>Follow day / night</option></select></section><section class="overlay" id="settings-panel" hidden><button class="close" onclick="this.parentElement.hidden=true">×</button><h2>BAZZITE HOST</h2><p>This is a simulated dashboard. The companion must run on the Bazzite host to supply actual resources.</p><p>The font and LED controls shown here have not been installed on the physical panel.</p><p>NeoPixel GPIO and connector selection await the exact LED product and board pin review.</p></section></div></div>'''
js='''const panel=document.querySelector('#led-panel');document.querySelector('#led').onclick=()=>panel.hidden=false;document.querySelector('#close').onclick=()=>panel.hidden=true;document.querySelector('#settings').onclick=()=>document.querySelector('#settings-panel').hidden=false;let on=true,color='#ffc7d5',name='Sakura';function update(){let b=document.querySelector('#brightness').value;document.querySelector('#percent').textContent=b+'%';document.querySelector('#preview-state').textContent=on?name+' / '+b+'%':'Lights off';let i=document.querySelector('#indicator');i.style.background=on?color:'#17201c';i.style.boxShadow=on?'0 0 16px '+color:'none';i.style.opacity=on?.2+.8*b/100:1;document.querySelector('#power').textContent=on?'LIGHTS ON':'LIGHTS OFF'}document.querySelector('#power').onclick=()=>{on=!on;update()};document.querySelector('#brightness').oninput=update;document.querySelectorAll('.swatch').forEach(b=>b.onclick=()=>{color=b.dataset.color;name=b.dataset.name;update()});document.querySelector('#sound').onclick=e=>e.target.textContent=e.target.textContent==='MUTED'?'MUTE / SOUND':'MUTED';document.querySelector('.sleep').onclick=()=>{document.querySelector('#card').style.opacity='.25';document.querySelector('#screen').style.filter='brightness(.35)'};document.querySelector('#scene').onclick=()=>{document.querySelector('#card').style.opacity='1';document.querySelector('#screen').style.filter='none'};'''
notes='''<div class="notes"><h1>Bazzite &bull; day scene / LED controller concept</h1><p>800 &times; 480 active pixels. DroidSansM Nerd Font Mono throughout. Ivory titles and lantern-orange values (#FFC477). Click LED CONTROLLER for simulated controls; nothing is sent to hardware.</p><p>Outer size 120.7 &times; 76.3 mm. Bezel: 3.5 mm top / 7.5 mm bottom. Active area modeled as 108 &times; 65.3 mm, centered horizontally. Native PNG remains 800 &times; 480; the physical illustration uses slight vertical scaling. Print at 100% / Actual size.</p><p>Example readings only; RAM assumes approximately 8 GiB assigned to the OS. The scene is an unchanged frame from the supplied day video.</p><div class="ruler">50 mm print check</div></div>'''
document='<!doctype html><html><meta charset="utf-8"><title>Bazzite panel concept</title><style>'+css+'</style>'+body+notes+'<script>'+js+'</script></html>'
(OUT/'bazzite-interactive-preview.html').write_text(document,encoding='utf-8')
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless=True)
 page=b.new_page(viewport={'width':1000,'height':950},device_scale_factor=1)
 page.goto((OUT/'bazzite-interactive-preview.html').as_uri());page.evaluate('document.fonts.ready')
 assert page.evaluate('document.fonts.check(\'24px Droid\')')
 page.locator('#screen').evaluate("e=>e.style.transform='none'")
 page.locator('#screen').screenshot(path=str(OUT/'bazzite-day-native.png'))
 page.locator('#screen').evaluate("e=>e.style.transform=''")
 page.locator('#device').screenshot(path=str(OUT/'bazzite-day-bezel.png'))
 page.locator('#led').click();assert page.locator('#led-panel').is_visible()
 page.locator('#brightness').fill('45');page.locator('[data-name="Onsen"]').click()
 assert page.locator('#preview-state').inner_text()=='Onsen / 45%'
 page.locator('#screen').evaluate("e=>e.style.transform='none'")
 page.locator('#screen').screenshot(path=str(OUT/'bazzite-led-controls.png'))
 page.locator('#power').click();assert page.locator('#preview-state').inner_text()=='Lights off'
 page.locator('#close').click();assert not page.locator('#led-panel').is_visible()
 b.close()
(OUT/'README.md').write_text('''# Bazzite preview\n\nUI mockup only, not flashed firmware. Open bazzite-interactive-preview.html; the LED button opens a working local interaction preview with power, colors, brightness and effect selection. No hardware connection is made.\n\nThe PNG active area is exactly 800x480. The black bezel is horizontally centered and raised vertically: 3.5mm top / 7.5mm bottom with a modeled 108x65.3mm active area. Overall size is 120.7x76.3mm, as requested. Native PNGs remain 800x480; the bezel illustration applies slight vertical scaling. Print the HTML at Actual size / 100% for physical dimensions; on-screen size depends on monitor scaling.\n\nFont: DroidSansM Nerd Font Mono, from https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/DroidSansMono . Font license is included under fonts/. The HTML embeds its font and video frame for offline viewing.\n\nReadings are simulated light-desktop values, not Bazzite benchmarks. The planned count is 48 RGB pixels (two 24-pixel rings). Exact NeoPixel product, connector and a confirmed free ESP32-P4 GPIO are required before implementing its output.\n''',encoding='utf-8')
print('Rendered Bazzite screenshots; LED open/color/brightness/power/close interactions passed.')
